#Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mtech
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-myapp
  namespace: mtech
spec:
  replicas: 3
  selector:
    matchLabels:
      app: webserver-simple-app
  template:
    metadata:
      labels:
        app: webserver-simple-app
    spec:
      containers:
        - name: webserver-simple-container
          image: python:3
          command:
            - python
            - -m
            - http.server
          ports:
            - containerPort: 8000
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: webserver-simple-service
  namespace: mtech
spec:
  selector:
    app: webserver-simple-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---

apiVersion: v1
kind: Pod
metadata:
  name: webserver-pod
  namespace: mtech
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    ports:
    - containerPort: 80